FROM golang:1.23.3

WORKDIR /app

# Copy the application source code
COPY . .

# Build the aggregator binary
RUN go build -o aggregator ./cmd/aggregator/main.go

# Set the default command to run the aggregator binary
CMD ["./aggregator"]
