name: Blockchain Data Aggregator CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Configure gcloud
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker images
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/aggregator:latest -f Dockerfile.aggregator .
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/token-prices:latest -f Dockerfile.token-prices .

    - name: Push Docker images to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/aggregator:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/token-prices:latest

    - name: Terraform Init
      run: |
        cd deploy
        terraform init

    - name: Terraform Apply
      env:
        TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        TF_VAR_region: "us-central1"
        TF_VAR_bucket_name: "aggregator-data"
        TF_VAR_clickhouse_host: ${{ secrets.CLICKHOUSE_HOST }}
        TF_VAR_clickhouse_port: "9440"
        TF_VAR_clickhouse_user: ${{ secrets.CLICKHOUSE_USER }}
        TF_VAR_clickhouse_password: ${{ secrets.CLICKHOUSE_PASSWORD }}
        TF_VAR_coingecko_api_key: ${{ secrets.COINGECKO_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        cd deploy
        terraform apply -auto-approve
