name: Blockchain Data Aggregator CD pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Create .env from .env.example
      run: |
        cp .env.example .env
        sed -i 's/your-project-id/${{ secrets.TF_VAR_PROJECT_ID }}/g' .env
        sed -i 's/your-region/${{ secrets.TF_VAR_REGION }}/g' .env
        sed -i 's/your-bucket-name/${{ secrets.TF_VAR_BUCKET_NAME }}/g' .env
        sed -i 's/your-clickhouse-host/${{ secrets.CLICKHOUSE_HOST }}/g' .env
        sed -i 's/your-clickhouse-port/${{ secrets.CLICKHOUSE_PORT }}/g' .env
        sed -i 's/your-clickhouse-user/${{ secrets.CLICKHOUSE_USER }}/g' .env
        sed -i 's/your-clickhouse-password/${{ secrets.CLICKHOUSE_PASSWORD }}/g' .env
        sed -i 's/your-coingecko-api-key/${{ secrets.COINGECKO_API_KEY }}/g' .env
        sed -i 's/your-log-level/${{ secrets.LOG_LEVEL }}/g' .env

    - name: Build Docker Images
      run: |
        docker build -t gcr.io/${{ secrets.TF_VAR_PROJECT_ID }}/aggregator:latest -f Dockerfile.aggregator .
        docker build -t gcr.io/${{ secrets.TF_VAR_PROJECT_ID }}/token-prices:latest -f Dockerfile.prices .

    - name: Push Docker Images
      run: |
        docker push gcr.io/${{ secrets.TF_VAR_PROJECT_ID }}/aggregator:latest
        docker push gcr.io/${{ secrets.TF_VAR_PROJECT_ID }}/token-prices:latest

    - name: Terraform Init
      run: |
        cd deploy
        terraform init

    - name: Terraform Apply
      env:
        TF_VAR_project_id: ${{ secrets.TF_VAR_PROJECT_ID }}
        TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
        TF_VAR_bucket_name: ${{ secrets.TF_VAR_BUCKET_NAME }}
        CLICKHOUSE_HOST: ${{ secrets.CLICKHOUSE_HOST }}
        CLICKHOUSE_PORT: ${{ secrets.CLICKHOUSE_PORT }}
        CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
        CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: |
        cd deploy
        terraform apply -auto-approve
