name: Blockchain Data Aggregator CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linelint
        uses: fernandrone/linelint@0.0.6
        id: linelint

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          args: --timeout 5m

      - name: Create .env from .env.example
        run: |
          cp .env.example .env
          sed -i 's/your-project-id/${{ secrets.TF_VAR_PROJECT_ID }}/g' .env
          sed -i 's/your-region/${{ secrets.TF_VAR_REGION }}/g' .env
          sed -i 's/your-bucket-name/${{ secrets.TF_VAR_BUCKET_NAME }}/g' .env
          sed -i 's/your-clickhouse-host/${{ secrets.CLICKHOUSE_HOST }}/g' .env
          sed -i 's/your-clickhouse-port/${{ secrets.CLICKHOUSE_PORT }}/g' .env
          sed -i 's/your-clickhouse-user/${{ secrets.CLICKHOUSE_USER }}/g' .env
          sed -i 's/your-clickhouse-password/${{ secrets.CLICKHOUSE_PASSWORD }}/g' .env
          sed -i 's/your-coingecko-api-key/${{ secrets.COINGECKO_API_KEY }}/g' .env
          sed -i 's/your-log-level/${{ secrets.LOG_LEVEL }}/g' .env

      - name: Check compilation
        run: |
          make build-local
