name: Build and Deploy Chain Data Aggregator Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linelint
        uses: fernandrone/linelint@0.0.6
        id: linelint

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          args: --timeout 5m

      - name: Check compilation
        run: |
          make build
